### ISSUE TITLE
stop-words.txt not found

### ISSUE THREAD

**Issue by zhihaowang9** [miroslavtushev/Domain-Specific-Analysis-of-Mobile-App-Reviews-Using-Keyword-Assisted-Topic-Models#1]
In the readme file, it says"`stop_words.txt` -> additional cohort-specific stop-words.".But I can't find the file in the list. I hope that the file can be uploaded.

**Comment by miroslavtushev** [comment]
[stop_words.txt](https://github.com/miroslavtushev/Domain-Specific-Analysis-of-Mobile-App-Reviews-Using-Keyword-Assisted-Topic-Models/files/9420119/stop_words.txt)
please see attached

**Comment by zhihaowang9** [comment]
Thanks！
